# Generated by Django 5.0 on 2024-01-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('NONE', 'None'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='NONE', max_length=6),
        ),
    ]
